#+LEVEL: 3
#+OPTIONS: H:3
#+BEAMER_HEADER: \usepackage{tikz-cd}

#+SELECT_TAGS: focus


* Algebraic structures

** Semigroups
*** Semigroup

   A [[https://en.wikipedia.org/wiki/Semigroup][semigroup]] is a set equipped with one binary operation (*) that satisfies:

   - *closure*
   - *associativity*

** Groups                                                             :focus:
*** Introduction

   A [[https://en.wikipedia.org/wiki/Group_(mathematics)][group]] is a monoid where for all elements $a$, the (*) operation satisfies:

   - *invertibility*: $a * a^{-1} = 1$.
   - *associativity*: $a * (b * c) = (a * b) * c$

   In a group, every element has its own inverse.

*** Subgroup
   A [[https://en.wikipedia.org/wiki/Subgroup][subgroup]] of $G$ is a subset $H$ of $G$ is called a subgroup of $G$ if $H$ also forms
   a group under the operation *.

   The *trivial subgroup* of any group is the subgroup ${e}$ consisting of just the identity element.

*** Coset                                                             :focus:
    Given a subgroup $H$ and some $a$ in $G$, we define the *left coset* of $H$ as
    $aH = \{ah : h \in H\}$. We have some properties holding:

    - each $a$ generates a subset of $G$ and, considering all the elements $a$
      of $G$, the corresponding set of cosets of $H$ is a partition of $G$.

    - all cosets of H have the same amount of elements (which is the same number of element of H).

    - because the family of cosets is a partition, the size of $G$ is a multiple of $H$ and its cosets.

